import { describe, it, expect } from 'vitest';
import { computeMetrics } from './metrics.js';
import type { Language } from './types.js';

describe('metrics', () => {
  it('computes metrics for a simple language', async () => {
    const language: Language = {
      pairs: [
        { meaningId: 'm000', form: 'papa' },
        { meaningId: 'm001', form: 'titi' },
        { meaningId: 'm002', form: 'kaka' },
        { meaningId: 'm003', form: 'mama' },
        { meaningId: 'm004', form: 'nana' },
        { meaningId: 'm005', form: 'sasa' },
        { meaningId: 'm006', form: 'lala' },
        { meaningId: 'm007', form: 'wawa' },
        { meaningId: 'm008', form: 'jaja' },
        { meaningId: 'm009', form: 'haha' },
        { meaningId: 'm010', form: 'pepe' },
        { meaningId: 'm011', form: 'tete' },
        { meaningId: 'm012', form: 'keke' },
        { meaningId: 'm013', form: 'meme' },
        { meaningId: 'm014', form: 'nene' },
        { meaningId: 'm015', form: 'sese' },
        { meaningId: 'm016', form: 'lele' },
        { meaningId: 'm017', form: 'wewe' },
        { meaningId: 'm018', form: 'jeje' },
        { meaningId: 'm019', form: 'hehe' },
        { meaningId: 'm020', form: 'pipi' },
        { meaningId: 'm021', form: 'titi' },
        { meaningId: 'm022', form: 'kiki' },
        { meaningId: 'm023', form: 'mimi' },
        { meaningId: 'm024', form: 'nini' },
        { meaningId: 'm025', form: 'sisi' },
        { meaningId: 'm026', form: 'lili' },
        { meaningId: 'm027', form: 'wiwi' },
        { meaningId: 'm028', form: 'jiji' },
        { meaningId: 'm029', form: 'hihi' },
        { meaningId: 'm030', form: 'pupu' },
        { meaningId: 'm031', form: 'tutu' },
        { meaningId: 'm032', form: 'kuku' },
        { meaningId: 'm033', form: 'mumu' },
        { meaningId: 'm034', form: 'nunu' },
        { meaningId: 'm035', form: 'susu' },
        { meaningId: 'm036', form: 'lulu' },
        { meaningId: 'm037', form: 'wuwu' },
        { meaningId: 'm038', form: 'juju' },
        { meaningId: 'm039', form: 'huhu' },
        { meaningId: 'm040', form: 'popo' },
        { meaningId: 'm041', form: 'toto' },
        { meaningId: 'm042', form: 'koko' },
        { meaningId: 'm043', form: 'momo' },
        { meaningId: 'm044', form: 'nono' },
        { meaningId: 'm045', form: 'soso' },
        { meaningId: 'm046', form: 'lolo' },
        { meaningId: 'm047', form: 'wowo' },
        { meaningId: 'm048', form: 'jojo' },
        { meaningId: 'm049', form: 'hoho' },
        { meaningId: 'm050', form: 'pua' },
        { meaningId: 'm051', form: 'tua' },
        { meaningId: 'm052', form: 'kua' },
        { meaningId: 'm053', form: 'mua' },
        { meaningId: 'm054', form: 'nua' },
        { meaningId: 'm055', form: 'sua' },
        { meaningId: 'm056', form: 'lua' },
        { meaningId: 'm057', form: 'wua' },
        { meaningId: 'm058', form: 'jua' },
        { meaningId: 'm059', form: 'hua' },
        { meaningId: 'm060', form: 'pae' },
        { meaningId: 'm061', form: 'tae' },
        { meaningId: 'm062', form: 'kae' },
        { meaningId: 'm063', form: 'mae' },
        { meaningId: 'm064', form: 'nae' },
        { meaningId: 'm065', form: 'sae' },
        { meaningId: 'm066', form: 'lae' },
        { meaningId: 'm067', form: 'wae' },
        { meaningId: 'm068', form: 'jae' },
        { meaningId: 'm069', form: 'hae' },
        { meaningId: 'm070', form: 'pai' },
        { meaningId: 'm071', form: 'tai' },
        { meaningId: 'm072', form: 'kai' },
        { meaningId: 'm073', form: 'mai' },
        { meaningId: 'm074', form: 'nai' },
        { meaningId: 'm075', form: 'sai' },
        { meaningId: 'm076', form: 'lai' },
        { meaningId: 'm077', form: 'wai' },
        { meaningId: 'm078', form: 'jai' },
        { meaningId: 'm079', form: 'hai' },
        { meaningId: 'm080', form: 'pao' },
        { meaningId: 'm081', form: 'tao' },
        { meaningId: 'm082', form: 'kao' },
        { meaningId: 'm083', form: 'mao' },
        { meaningId: 'm084', form: 'nao' },
        { meaningId: 'm085', form: 'sao' },
        { meaningId: 'm086', form: 'lao' },
        { meaningId: 'm087', form: 'wao' },
        { meaningId: 'm088', form: 'jao' },
        { meaningId: 'm089', form: 'hao' },
        { meaningId: 'm090', form: 'pau' },
        { meaningId: 'm091', form: 'tau' },
        { meaningId: 'm092', form: 'kau' },
        { meaningId: 'm093', form: 'mau' },
        { meaningId: 'm094', form: 'nau' },
        { meaningId: 'm095', form: 'sau' },
        { meaningId: 'm096', form: 'lau' },
        { meaningId: 'm097', form: 'wau' },
        { meaningId: 'm098', form: 'jau' },
        { meaningId: 'm099', form: 'hau' },
        { meaningId: 'm100', form: 'pa' },
        { meaningId: 'm101', form: 'te' },
        { meaningId: 'm102', form: 'ki' },
        { meaningId: 'm103', form: 'mo' },
        { meaningId: 'm104', form: 'nu' },
        { meaningId: 'm105', form: 'sa' },
        { meaningId: 'm106', form: 'le' },
        { meaningId: 'm107', form: 'wi' },
        { meaningId: 'm108', form: 'jo' },
        { meaningId: 'm109', form: 'hu' },
        { meaningId: 'm110', form: 'pta' },
        { meaningId: 'm111', form: 'tka' },
        { meaningId: 'm112', form: 'kma' },
        { meaningId: 'm113', form: 'mna' },
        { meaningId: 'm114', form: 'nsa' },
        { meaningId: 'm115', form: 'sla' },
        { meaningId: 'm116', form: 'lwa' },
        { meaningId: 'm117', form: 'wja' },
        { meaningId: 'm118', form: 'jha' },
        { meaningId: 'm119', form: 'hpa' },
        { meaningId: 'm120', form: 'pte' },
        { meaningId: 'm121', form: 'tke' },
        { meaningId: 'm122', form: 'kme' },
        { meaningId: 'm123', form: 'mne' },
        { meaningId: 'm124', form: 'nse' },
        { meaningId: 'm125', form: 'sle' },
        { meaningId: 'm126', form: 'lwe' },
        { meaningId: 'm127', form: 'wje' },
        { meaningId: 'm128', form: 'jhe' },
        { meaningId: 'm129', form: 'hpe' },
        { meaningId: 'm130', form: 'pti' },
        { meaningId: 'm131', form: 'tki' },
        { meaningId: 'm132', form: 'kmi' },
        { meaningId: 'm133', form: 'mni' },
        { meaningId: 'm134', form: 'nsi' },
        { meaningId: 'm135', form: 'sli' },
        { meaningId: 'm136', form: 'lwi' },
        { meaningId: 'm137', form: 'wji' },
        { meaningId: 'm138', form: 'jhi' },
        { meaningId: 'm139', form: 'hpi' },
        { meaningId: 'm140', form: 'pto' },
        { meaningId: 'm141', form: 'tko' },
        { meaningId: 'm142', form: 'kmo' },
        { meaningId: 'm143', form: 'mno' },
        { meaningId: 'm144', form: 'nso' },
        { meaningId: 'm145', form: 'slo' },
        { meaningId: 'm146', form: 'lwo' },
        { meaningId: 'm147', form: 'wjo' },
        { meaningId: 'm148', form: 'jho' },
        { meaningId: 'm149', form: 'hpo' },
        { meaningId: 'm150', form: 'ptu' },
        { meaningId: 'm151', form: 'tku' },
        { meaningId: 'm152', form: 'kmu' },
        { meaningId: 'm153', form: 'mnu' },
        { meaningId: 'm154', form: 'nsu' },
        { meaningId: 'm155', form: 'slu' },
        { meaningId: 'm156', form: 'lwu' },
        { meaningId: 'm157', form: 'wju' },
        { meaningId: 'm158', form: 'jhu' },
        { meaningId: 'm159', form: 'hpu' },
        { meaningId: 'm160', form: 'ppa' },
        { meaningId: 'm161', form: 'tte' },
        { meaningId: 'm162', form: 'kki' },
        { meaningId: 'm163', form: 'mmo' },
        { meaningId: 'm164', form: 'nnu' },
        { meaningId: 'm165', form: 'ssa' },
        { meaningId: 'm166', form: 'lle' },
        { meaningId: 'm167', form: 'wwi' },
        { meaningId: 'm168', form: 'jjo' },
        { meaningId: 'm169', form: 'hhu' },
        { meaningId: 'm170', form: 'ppa' },
        { meaningId: 'm171', form: 'tte' },
        { meaningId: 'm172', form: 'kki' },
        { meaningId: 'm173', form: 'mmo' },
        { meaningId: 'm174', form: 'nnu' },
        { meaningId: 'm175', form: 'ssa' },
        { meaningId: 'm176', form: 'lle' },
        { meaningId: 'm177', form: 'wwi' },
        { meaningId: 'm178', form: 'jjo' },
        { meaningId: 'm179', form: 'hhu' },
        { meaningId: 'm180', form: 'pppa' },
        { meaningId: 'm181', form: 'ttte' },
        { meaningId: 'm182', form: 'kkki' },
        { meaningId: 'm183', form: 'mmmo' },
        { meaningId: 'm184', form: 'nnnu' },
        { meaningId: 'm185', form: 'ssaa' },
        { meaningId: 'm186', form: 'llee' },
        { meaningId: 'm187', form: 'wwii' },
        { meaningId: 'm188', form: 'jjoo' },
        { meaningId: 'm189', form: 'hhuu' },
        { meaningId: 'm190', form: 'ppep' },
        { meaningId: 'm191', form: 'ttet' },
        { meaningId: 'm192', form: 'kkik' },
        { meaningId: 'm193', form: 'mmom' },
        { meaningId: 'm194', form: 'nnun' },
        { meaningId: 'm195', form: 'ssas' },
        { meaningId: 'm196', form: 'llel' },
        { meaningId: 'm197', form: 'wwiw' },
        { meaningId: 'm198', form: 'jjoj' },
        { meaningId: 'm199', form: 'hhuh' },
      ],
    };

    const inSampleMeaningIds = new Set(
      ['m000', 'm001', 'm002', 'm003', 'm004', 'm005', 'm006', 'm007', 'm008', 'm009']
    );

    const metrics = await computeMetrics(language, null, inSampleMeaningIds);

    expect(metrics.lexiconStats.uniqueFormCount).toBeGreaterThan(0);
    expect(metrics.lexiconStats.meanFormLength).toBeGreaterThan(0);
    expect(metrics.compositionality.pearsonCorrelation).toBeDefined();
    expect(metrics.compressibility.compressionRatio).toBeGreaterThan(0);
  });

  it('computes transmission fidelity when previous language exists', async () => {
    const previous: Language = {
      pairs: [
        { meaningId: 'm000', form: 'papa' },
        { meaningId: 'm001', form: 'titi' },
      ],
    };

    const current: Language = {
      pairs: [
        { meaningId: 'm000', form: 'papa' },
        { meaningId: 'm001', form: 'tate' },
      ],
    };

    const inSampleMeaningIds = new Set(['m000']);
    const metrics = await computeMetrics(current, previous, inSampleMeaningIds);

    expect(metrics.transmissionFidelity.overall.exactMatchRate).toBeLessThanOrEqual(1);
    expect(metrics.transmissionFidelity.inSample.exactMatchRate).toBe(1);
    expect(metrics.transmissionFidelity.heldOut.exactMatchRate).toBe(0);
  });
});
